---
title: "Blodtryksmålinger"
format: html
execute:
  echo: false
  warning: false
  message: false
---

```{r setup}
library(tidyverse)
library(readxl)
blodtryk <- read_excel("L:/LovbeskyttetMapper/AID projekt - Collab grant/WP2+3 (AIDBeyond)/AID-BEYOND Trial Master File/16) Data analyser/Analyseskema samlet NY.xlsx", 
    sheet = "Blodtryk")
blodtryksort <- blodtryk |> 
  filter(`Færdig?`=="Ja")
```

## Blodtryk:
Alle inkluderede deltagere har udført døgnblodtryksmålinger. Følgende målinger er fundet:

### For de samlede 24 timers målinger:
```{r}
#| label: fig-24-bt-change
#| fig-cap: "Gennemsnitligt blodtryk over 24 timer"
#| fig-subcap:
#| - "Systolisk tryk"
#| - "Diastolisk tryk"
#| - "MAP"
#| layout-ncol: 3
blodtryksort |> 
  rename("mmHg" = "24 Middel sys") |> 
  ggplot(aes(x = Visit, y = `mmHg`, colour = Gruppe, group = Deltager)) +
  geom_point() + 
  geom_line()

blodtryksort |> 
  rename("mmHg" = "24 Middel dia") |> 
  ggplot(aes(x = Visit, y = `mmHg`, colour = Gruppe, group = Deltager)) +
  geom_point() + 
  geom_line()

blodtryksort |> 
  rename("mmHg" = "24 MAP") |> 
  ggplot(aes(x = Visit, y = `mmHg`, colour = Gruppe, group = Deltager)) +
  geom_point() + 
  geom_line()
```

```{r}
#| label: fig-24-bt-box-change
#| fig-cap: "Gennemsnitligt blodtryk over 24 timer"
#| fig-subcap:
#| - "Systolisk tryk"
#| - "Diastolisk tryk"
#| - "MAP"
#| layout-ncol: 3
blodtryksort |> 
  rename("mmHg" = "24 Middel sys") |> 
  ggplot(aes(x = Visit, y = `mmHg`, colour = Gruppe)) +
  geom_boxplot()

blodtryksort |> 
  rename("mmHg" = "24 Middel dia") |> 
  ggplot(aes(x = Visit, y = `mmHg`, colour = Gruppe)) +
  geom_boxplot()

blodtryksort |> 
  rename("mmHg" = "24 MAP") |> 
  ggplot(aes(x = Visit, y = `mmHg`, colour = Gruppe)) +
  geom_boxplot()
```

### Målinger for vågen / søvn perioder. For overblikkets skyld anvendes kun MAP her:
```{r}
#| label: fig-dagnat-bt-change
#| fig-cap: "Gennemsnitligt MAP for vågen/søvn"
#| fig-subcap:
#| - "MAP vågen periode"
#| - "MAP søvn periode"
#| layout-ncol: 2
blodtryksort |> 
  rename("mmHg" = "MAP vågen") |> 
  ggplot(aes(x = Visit, y = `mmHg`, colour = Gruppe, group = Deltager)) +
  geom_point() + 
  geom_line()

blodtryksort |> 
  rename("mmHg" = "MAP søvn") |> 
  ggplot(aes(x = Visit, y = `mmHg`, colour = Gruppe, group = Deltager)) +
  geom_point() + 
  geom_line()
```

### Antal af "Dippers" målt på fald i MAP om natten ift. dagen (defineret som minus 10%):
```{r}
#| label: fig-dippers-change
#| fig-cap: "Samlet antal Dippers ved start og slut"
#| fig-subcap:
#| - "Dippers, baseline"
#| - "Dippers, follow-up"
#| layout-ncol: 2
blodtryksort |> 
  filter(`Visit`=="Baseline") |> 
  ggplot(aes(x = Gruppe, fill = as.character(Dipper))) +
  geom_bar(position = position_dodge()) +
  ylim(0, 8)

blodtryksort |> 
  filter(`Visit`=="Follow-up") |> 
  ggplot(aes(x = Gruppe, fill = as.character(Dipper))) +
  geom_bar(position = position_dodge()) +
  ylim(0, 8)
```
