---
title: "G7 data"
format: html
execute:
  echo: false
  warning: false
  message: false
---

```{r}
library(tidyverse)
library(readxl)

#Usual care follow-up analyser
controlbaseline <- list.files(
  path = "L:/LovbeskyttetMapper/AID projekt - Collab grant/WP2+3 (AIDBeyond)/AID-BEYOND Trial Master File/16) Data analyser/G7/Control/Baseline",
  pattern = "\\.csv$",
  full.names = T
  ) |>
  map_df(~ read_csv(., col_types = cols(.default = "c")))

#AID baseline analyser
aidbaseline <- list.files(
  path = "L:/LovbeskyttetMapper/AID projekt - Collab grant/WP2+3 (AIDBeyond)/AID-BEYOND Trial Master File/16) Data analyser/G7/AID/Baseline",
  pattern = "\\.csv$",
  full.names = T
  ) |>
  map_df(~ read_csv(., col_types = cols(.default = "c")))

#Usual care follow-up analyser
controlfollowup <- list.files(
  path = "L:/LovbeskyttetMapper/AID projekt - Collab grant/WP2+3 (AIDBeyond)/AID-BEYOND Trial Master File/16) Data analyser/G7/Control/Followup",
  pattern = "\\.csv$",
  full.names = T
  ) |>
  map_df(~ read_csv(., col_types = cols(.default = "c")))

#AID follow-up analyser
aidfollowup <- list.files(
  path = "L:/LovbeskyttetMapper/AID projekt - Collab grant/WP2+3 (AIDBeyond)/AID-BEYOND Trial Master File/16) Data analyser/G7/AID/Followup",
  pattern = "\\.csv$",
  full.names = T
  ) |>
  map_df(~ read_csv(., col_types = cols(.default = "c")))

g7 <- read_excel("L:/LovbeskyttetMapper/AID projekt - Collab grant/WP2+3 (AIDBeyond)/AID-BEYOND Trial Master File/16) Data analyser/Analyseskema samlet NY.xlsx", 
    sheet = "G7")
g7sort <- g7 |> 
  filter(`Færdig`=="Ja")
```

```{r}
#Forsimplede datasæt
controlbaselinesimple <- controlbaseline |>
  select(`Timestamp (YYYY-MM-DDThh:mm:ss)`, `Glucose Value (mmol/L)`) |>
  rename(
    Tid = `Timestamp (YYYY-MM-DDThh:mm:ss)`,
    Glucose = `Glucose Value (mmol/L)`
    ) |>
   filter(
     Glucose <= 25 | Glucose >= 0,
     Tid >= 0
     ) |> 
    mutate(
    SubTid = str_replace_all(Tid, "-", "/"),
    SubTid2 = str_replace_all(SubTid, "T", " "),
    endeligtid = hour(SubTid2),
    fiksglucose = str_replace_all(Glucose, "High", "22.5"),
    endeligglucose = as.numeric(fiksglucose)
    ) |>
  select(Tid, endeligtid, Glucose, endeligglucose)

aidbaselinesimple <- aidbaseline |>
  select(`Timestamp (YYYY-MM-DDThh:mm:ss)`, `Glucose Value (mmol/L)`) |>
  rename(
    Tid = `Timestamp (YYYY-MM-DDThh:mm:ss)`,
    Glucose = `Glucose Value (mmol/L)`
    ) |>
   filter(
     Glucose <= 25 | Glucose >= 0,
     Tid >= 0
     ) |>  
    mutate(
    SubTid = str_replace_all(Tid, "-", "/"),
    SubTid2 = str_replace_all(SubTid, "T", " "),
    endeligtid = hour(SubTid2),
    fiksglucose = str_replace_all(Glucose, "High", "22.5"),
    endeligglucose = as.numeric(fiksglucose)
    ) |>
  select(endeligtid, Glucose, endeligglucose)

controlfollowupsimple <- controlfollowup |>
  select(`Timestamp (YYYY-MM-DDThh:mm:ss)`, `Glucose Value (mmol/L)`) |>
  rename(
    Tid = `Timestamp (YYYY-MM-DDThh:mm:ss)`,
    Glucose = `Glucose Value (mmol/L)`
    ) |>
   filter(
     Glucose <= 25 | Glucose >= 0,
     Tid >= 0
     ) |>  
    mutate(
    SubTid = str_replace_all(Tid, "-", "/"),
    SubTid2 = str_replace_all(SubTid, "T", " "),
    endeligtid = hour(SubTid2),
    fiksglucose = str_replace_all(Glucose, "High", "22.5"),
    endeligglucose = as.numeric(fiksglucose)
    ) |>
  select(endeligtid,Glucose, endeligglucose)

aidfollowupsimple <- aidfollowup |>
  select(`Timestamp (YYYY-MM-DDThh:mm:ss)`, `Glucose Value (mmol/L)`) |>
  rename(
    Tid = `Timestamp (YYYY-MM-DDThh:mm:ss)`,
    Glucose = `Glucose Value (mmol/L)`
    ) |>
   filter(
     Glucose <= 25 | Glucose >= 0,
     Tid >= 0
     ) |>  
    mutate(
    SubTid = str_replace_all(Tid, "-", "/"),
    SubTid2 = str_replace_all(SubTid, "T", " "),
    endeligtid = hour(SubTid2),
    fiksglucose = str_replace_all(Glucose, "High", "22.5"),
    endeligglucose = as.numeric(fiksglucose)
    ) |>
  select(endeligtid,Glucose, endeligglucose)
```
## Antal deltagere:
```{r}
g7sort |> 
count(`Gruppe`) |> 
  knitr::kable()
```


To deltagere i kontrol gruppe udelukket grundet G7 målinger ikke er trukket fra clarity, så kan ikke få data til at fungere med R script. Finder en løsning senere.

## G7 værdier ved baseline og followup:
```{r}
g7sort |> 
  group_by(`Gruppe`,`Basetreat`) |> 
  summarise(
    "TIR baseline" = mean(TIR_før),
    "TAR baseline" = mean(TAR_før),
    "TBR baseline" = mean(TBR_før),
    "TIR ændring" = mean(TIR_ændring),
    "TAR ændring" = mean(TAR_ændring),
    "TBR ændring" = mean(TBR_ændring)
  ) |> 
  knitr::kable()
```


## Baseline målinger:
```{r}
#| label: fig-g7-baseline
#| fig-subcap:
#| - "Kontrolgruppe"
#| - "AID"
#| layout-ncol: 2
ggplot(controlbaselinesimple, aes(x = endeligtid, y = endeligglucose)) +
  #geom_point(size = 0.5) +
  geom_hline(yintercept = 3.9) +
  geom_hline(yintercept = 10) +
  geom_smooth() +
  ylim(2,22) +
  labs(y="Blood glucose (mmol/L)",x="Time of day") +
  theme(text = element_text(size = 20))

ggplot(aidbaselinesimple, aes(x = endeligtid, y = endeligglucose)) +
  #geom_point(size = 0.5) +
  geom_hline(yintercept = 3.9) +
  geom_hline(yintercept = 10) +
  geom_smooth() +
  ylim(2,22) +
  labs(y="Blood glucose (mmol/L)",x="Time of day") +
  theme(text = element_text(size = 20))
```

## Follow-up målinger:
```{r}
#| label: fig-g7-followup
#| fig-subcap:
#| - "Kontrolgruppe"
#| - "AID"
#| layout-ncol: 2
ggplot(controlfollowupsimple, aes(x = endeligtid, y = endeligglucose)) +
  #geom_point(size = 0.5) +
  geom_hline(yintercept = 3.9) +
  geom_hline(yintercept = 10) +
  geom_smooth() +
  ylim(2,22) +
  labs(y="Blood glucose (mmol/L)",x="Time of day") +
  theme(text = element_text(size = 20))

ggplot(aidfollowupsimple, aes(x = endeligtid, y = endeligglucose)) +
  #geom_point(size = 0.5) +
  geom_hline(yintercept = 3.9) +
  geom_hline(yintercept = 10) +
  geom_smooth() +
  ylim(2,22) +
  labs(y="Blood glucose (mmol/L)",x="Time of day") +
  theme(text = element_text(size = 20))
```
